name: Automated checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: HTTP Server Action
        uses: Eun/http-server-action@v1
        with:
          port: 8070

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag encarno:$(date +%s)
