name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: HTTP Server Action
        uses: Eun/http-server-action@v1.0.3
        with:
          port: 8070

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          #token: {{your codecov token, can be found at https://codecov.io/gh/<github_username>/<repo>/settings/badge}}
          file: ./coverage.txt
          flags: unittests
